### ISSUE TITLE
Followers are not showing the right followers.

### ISSUE THREAD

**Issue by Alayode** [chrisksamueljr/cloning-github-User-interfaces#1]
Apparently when you visit the /user/:login page and click on the FOLLOWERS Tab you do not see the users actual followers. After so debugging the same followers are shown despite which user you view. 

Something is hard coded and needs to be fixed.

**Comment by Alayode** [comment]
page is working

**Comment by chrisksamueljr** [comment]
the branch configure-user-repos-followers-following resolved this issue
