### ISSUE TITLE
TypeError: g is undefined

### ISSUE THREAD

**Issue by Alayode** [chrisksamueljr/cloning-github-User-interfaces#3]
Seems to be an issue with the version of bootstrap we need to check out what is causing the error and fix it.

**Comment by Alayode** [comment]
Remove this link below:
stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js


https://ng-bootstrap.github.io/#/getting-started

Needed to be removed in order to avoid this error.
 No, the goal of ng-bootstrap is to completely replace JavaScript implementation for components. Nor should you include other dependencies like jQuery or popper.js. It is not necessary and might interfere with ng-bootstrap code.

**Comment by chrisksamueljr** [comment]
Updated the ngBootstrap node package module and removed the bootstrap.min.js closing this issue
