### ISSUE TITLE
ERROR TypeError: "_co.repo is undefined"

### ISSUE THREAD

**Issue by Alayode** [chrisksamueljr/cloning-github-User-interfaces#4]
TopReposComponent.html:14:4

Seems to be coming from the TopReposComponent Template. This error usually means that there is something that is being invoke that is undefined. The property is possibly not available on the Component.

**Comment by Alayode** [comment]
modified the interface to grab the entire repo response instead of the repo

**Comment by chrisksamueljr** [comment]
Resolve in the branch use-repo-response-interface branch
